---
- name: Create prometheus user
  ansible.builtin.user:
    name: prometheus
    state: present
    shell: /sbin/nologin
  become_user: root

- name: Create directories for alertmanager
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
    - /etc/alertmanager
    - /var/lib/alertmanager

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: "{{ alertmanager_url }}"
    dest: /tmp
    mode: 0755
    remote_src: true

- name: Copy alertmanager
  ansible.builtin.copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"
    dest: "{{ alertmanager_bin_path }}"
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: true

- name: Delete unwanted files
  ansible.builtin.file:
    state: absent
    path: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64"

- name: Delete unwanted files
  ansible.builtin.file:
    state: absent
    path: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"

- name: Copy the alertmanager config file.
  ansible.builtin.copy:
    src: alertmanager.yml
    dest: /etc/alertmanager/alertmanager.yml
    owner: prometheus
    group: prometheus
    mode: 0755

- name: Copy the alertmanager systemd unit file.
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: 0644

- name: Start alertmanager
  ansible.builtin.systemd:
    state: started
    name: alertmanager
    daemon_reload: true
    enabled: true
