---
- name: Import node_exporter task
  ansible.builtin.import_tasks: node_exporter.yaml

- name: Import cadvisor task
  ansible.builtin.include_tasks: cadvisor.yaml
  when: docker_monitoring is defined and docker_monitoring|bool == True
