---
- name: Import process_exporter task
  ansible.builtin.import_tasks: process_exporter.yaml
# - name: Install Prometheus Agents
#   become: true
#   block:
#     - name: Import node_exporter task
#       ansible.builtin.import_tasks: node_exporter.yaml
# 
#     - name: Import cadvisor task
#       ansible.builtin.include_tasks: cadvisor.yaml
#       when: docker_monitoring | bool
# 
# - name: Set prometheus config
#   ansible.builtin.uri:
#     url: http://wfr-mondb-01.corp.mutualink.net:8000/api/config
#     method: POST
#     body_format: json
#     body:
#       docker_monitoring: "{{ docker_monitoring }}"
#       address: "{{ inventory_hostname }}"
#       job: "{{ job | default(omit) }}"
#   until: uri_output.status == 200
#   retries: 2
#   delay: 5
#   register: uri_output
#   delegate_to: localhost
